const Users = [
    {

        phone: "53517890",
        notification_permission: true,
        notification_token: "",
        insta: {
            last_scrape: "2023-08-15T12:00:00Z",
            id: "insta-user-1",
            access_token: "insta-access-token",
            username: "user1_insta",
            full_name: "User One",
            biography: "",
            profile_pic: "https://cdn.vox-cdn.com/thumbor/heXu37IbDvVy6Qbo1wbPjNvi6Ys=/0x0:712x423/1200x800/filters:focal(385x120:497x232)/cdn.vox-cdn.com/uploads/chorus_image/image/55531035/Screen_Shot_2017_06_30_at_3.17.00_PM.0.png",
            followers: 12400,
            following: 500,
            average_like: 150,
            post_number: 50,

        },
        tiktok: {
            username: "user1_tiktok",
            keywords: ["funny", "entertainment"],
            tiktok_last_scrape: "2023-08-15T12:00:00Z",
            tiktok_nickname: "TikTokUser1",
            bio_description: "assa",
            last_scrape: "2023-08-15T12:00:00Z",
            followers: 60000,
            following: 1000,
            hearts: 10000,

            profile_pic: "https://static.wikia.nocookie.net/rickandmorty/images/4/41/Pickle_rick_transparent_edgetrimmed.png/revision/latest?cb=20220105043415",

            tiktok_average_like: 800,
            tiktok_engagement_rate: 15,
            tiktok_access_token: "tiktok-access-token",
            tiktok_refresh_token: "tiktok-refresh-token",

        },
        job: "Pickle",
        name: "Pickle",
        surname: "Rick",
        score: 100,
        email: "picklepickle@example.com",

        age: 33,
        gender: "Male",
        profile_complete: true,
        school_type: "University",
        school_name: "Seattle University",
        password: 1231,
        passwordTime: "2023-08-15T12:00:00Z",
        city: "Seattle",
        country: "USA",
        language: "turkish",

        hobbies: ["Dancing", "Photography"],
        sharing_type: "Public",
        last_login: "2023-08-15T12:00:00Z",
        applications_update: "2023-08-15T12:00:00Z",
        hasNotificationPermission: true,
        onesignal_pushToken: "onesignal-push-token",
        onesignal_userId: "onesignal-user-id",
        latitude: "",
        longitude: "",
        timezone: "UTC-4",
        currency: "USD",
        verification: true,
        denied_verification: false,
        verification_last_action: "2023-08-15T12:00:00Z",
        deleted: false,

    },
    {

        phone: "53517890",
        notification_permission: true,
        notification_token: "",
        insta: {
            last_scrape: "2023-08-15T12:00:00Z",
            id: "insta-user-1",
            access_token: "insta-access-token",
            username: "user1_insta",
            full_name: "User One",
            biography: "",
            profile_pic: "https://static.wikia.nocookie.net/rickandmorty/images/4/41/Pickle_rick_transparent_edgetrimmed.png/revision/latest?cb=20220105043415",
            followers: 400,
            following: 500,
            average_like: 150,
            post_number: 50,

        },
        tiktok: {
            username: "user1_tiktok",
            keywords: ["funny", "entertainment"],
            tiktok_last_scrape: "2023-08-15T12:00:00Z",
            tiktok_nickname: "TikTokUser1",
            bio_description: "assa",
            last_scrape: "2023-08-15T12:00:00Z",
            followers: 60000,
            following: 1000,
            hearts: 10000,

            profile_pic: "https://static.wikia.nocookie.net/rickandmorty/images/4/41/Pickle_rick_transparent_edgetrimmed.png/revision/latest?cb=20220105043415",

            tiktok_average_like: 800,
            tiktok_engagement_rate: 15,
            tiktok_access_token: "tiktok-access-token",
            tiktok_refresh_token: "tiktok-refresh-token",

        },
        job: "Avukat",
        name: "Necip",
        surname: "Necipoğlu",
        score: 100,
        email: "necipoglu@example.com",

        age: 45,
        gender: "Male",
        profile_complete: true,
        school_type: "University",
        school_name: "Istanbul University",
        password: 1231,
        passwordTime: "2023-08-15T12:00:00Z",
        city: "Ankara",
        country: "Turkey",
        language: "turkish",

        hobbies: ["Traveling", "Photography"],
        sharing_type: "Public",
        last_login: "2023-08-15T12:00:00Z",
        applications_update: "2023-08-15T12:00:00Z",
        hasNotificationPermission: true,
        onesignal_pushToken: "onesignal-push-token",
        onesignal_userId: "onesignal-user-id",
        latitude: "",
        longitude: "",
        timezone: "UTC-4",
        currency: "USD",
        verification: true,
        denied_verification: false,
        verification_last_action: "2023-08-15T12:00:00Z",
        deleted: false,

    },
    {

        phone: "53517890",
        notification_permission: true,
        notification_token: "",
        insta: {
            last_scrape: "2023-08-15T12:00:00Z",
            id: "insta-user-1",
            access_token: "insta-access-token",
            username: "user1_insta",
            full_name: "User One",
            biography: "",
            profile_pic: "https://upload.wikimedia.org/wikipedia/en/e/eb/Knightni.jpg",
            followers: 850,
            following: 500,
            average_like: 150,
            post_number: 50,

        },
        tiktok: {
            username: "user1_tiktok",
            keywords: ["funny", "entertainment"],
            tiktok_last_scrape: "2023-08-15T12:00:00Z",
            tiktok_nickname: "TikTokUser1",
            bio_description: "assa",
            last_scrape: "2023-08-15T12:00:00Z",
            followers: 345,
            following: 1000,
            hearts: 10000,

            profile_pic: "https://upload.wikimedia.org/wikipedia/en/e/eb/Knightni.jpg",

            tiktok_average_like: 800,
            tiktok_engagement_rate: 15,
            tiktok_access_token: "tiktok-access-token",
            tiktok_refresh_token: "tiktok-refresh-token",

        },
        job: "Knight",
        name: "Knights",
        surname: "Who Says Ni",
        score: 100,
        email: "knights@example.com",

        age: 65,
        gender: "Male",
        profile_complete: true,
        school_type: "University",
        school_name: "Knight University",
        password: 1231,
        passwordTime: "2023-08-15T12:00:00Z",
        city: "Knightingale",
        country: "Turkey",
        language: "turkish",

        hobbies: ["Dancing", "Photography"],
        sharing_type: "Public",
        last_login: "2023-08-15T12:00:00Z",
        applications_update: "2023-08-15T12:00:00Z",
        hasNotificationPermission: true,
        onesignal_pushToken: "onesignal-push-token",
        onesignal_userId: "onesignal-user-id",
        latitude: "",
        longitude: "",
        timezone: "UTC-4",
        currency: "USD",
        verification: true,
        denied_verification: false,
        verification_last_action: "2023-08-15T12:00:00Z",
        deleted: false,

    },

    {
        firebase_id: "firebase-id",
        phone: "9876543210",
        notification_permission: true,
        notification_token: "",
        insta: {
            last_scrape: "2023-08-15T12:00:00Z",
            id: "insta-user",
            access_token: "insta-access-token-1",
            username: "user2_insta",
            full_name: "User Two",
            biography: "",
            profile_pic: "https://lumiere-a.akamaihd.net/v1/images/luke-skywalker-main_7ffe21c7.jpeg?region=130%2C147%2C1417%2C796",
            followers: 3000,
            following: 1000,
            average_like: 250,
            post_number: 75,

            keywords: ["nature", "photography"],
        },
        tiktok: {
            username: "user_tiktok",
            keywords: [],
            tiktok_last_scrape: "2023-08-15T12:00:00Z",
            tiktok_nickname: "TikTokUser2",
            bio_description: "sadas",
            last_scrape: "2023-08-15T12:00:00Z",
            followers: 8000,
            following: 2000,
            hearts: 20000,

            profile_pic: "https://lumiere-a.akamaihd.net/v1/images/luke-skywalker-main_7ffe21c7.jpeg?region=130%2C147%2C1417%2C796",
            createTime: "2019-05-01T00:00:00Z",
            privateAccount: false,
            verified: true,
            secret: false,
            tiktok_average_like: 1200,
            tiktok_engagement_rate: 20,
            tiktok_access_token: "tiktok-access",
            tiktok_refresh_token: "tiktok-refresh",
            open_id: "tiktok-open-id-1",
            refresh_expires_in: "3600",
            log_id: "log-id-1",
            union_id: "union-id-1",
        },
        job: " Jedi Master",
        name: "Luke",
        surname: "Skywalker",
        score: 150,
        email: "luke@jedi.com",
        birthday: "1988-100T00:00:00Z",
        birthday_lastupdate: "2023-08-15T00:00:00Z",
        age: 34,
        gender: "Male",
        profile_complete: true,
        school_type: "College",
        school_name: "Jedi Praxeum",
        password: 987654,
        passwordTime: "2023-08-15T12:00:00Z",
        city: "Tatooine",
        country: "Star",
        language: "English",

        hobbies: ["Dancing", "Painting"],
        sharing_type: "Friends",
        last_login: "2023-08-15T12:00:00Z",
        applications_update: "2023-08-15T12:00:00Z",
        hasNotificationPermission: true,
        onesignal_pushToken: "onesignal-push-token-1",
        onesignal_userId: "onesignal-user-id-1",
        latitude: 41.1234,
        longitude: -72.31,
        timezone: "UTC-5",
        currency: "USD",
        verification: true,
        denied_verification: false,
        verification_last_action: "2023-08-15T12:00:00Z",
        deleted: false,

    },
    {
        firebase_id: "firebase-id",
        phone: "55512317",
        notification_permission: false,
        notification_token: "",
        insta: {
            last_scrape: "2023-08-15T12:00:00Z",
            id: "insta-user-id",
            access_token: "insta-access-token",
            username: "dsaasd",
            full_name: "sdasda",
            biography: "",
            profile_pic: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=761&q=80",
            followers: 628,
            following: 567,
            average_like: 100,
            post_number: 25,
            shared_posts: [],
            keywords: [],
        },
        tiktok: {
            username: "alice.tiktok",
            keywords: ["dance", "comedy", "fun"],
            tiktok_last_scrape: "2023-08-14T15:30:00Z",
            tiktok_nickname: "",
            bio_description: "",
            last_scrape: "2023-08-14T15:30:00Z",
            followers: 17,
            following: 678,
            hearts: 98765,
            profile_pic: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=761&q=80",
            createTime: "2020-05-10T00:00:00Z",
            privateAccount: false,
            verified: false,
            secret: false,
            tiktok_average_like: 1500,
            tiktok_engagement_rate: 3.5,
            tiktok_access_token: "tiktok-access-token",
            tiktok_refresh_token: "tiktok-refresh-token",
            open_id: "tiktok-open-id",
            refresh_expires_in: "2023-09-15T12:00:00Z",
            log_id: "tiktok-log-id",
            union_id: "tiktok-union-id",
        },
        job: "Software Engineer",
        name: "Jenifer",
        surname: "jeniferson",
        score: 80,
        email: "jenifer@example.com",
        birthday: "1995-03-10T00:00:00Z",
        birthday_lastupdate: "2023-03-10T00:00:00Z",
        age: 28,
        gender: "Female",
        profile_complete: true,
        school_type: "University",
        school_name: "Tech University",
        password: "hashed-password",
        passwordTime: "2023-08-15T10:00:00Z",
        city: "New York",
        country: "United States",
        language: "English",

        hobbies: ["Hiking", "Photography", "Dancing"],
        sharing_type: "Friends",
        last_login: "2023-08-14T18:00:00Z",
        applications_update: "2023-08-15T08:00:00Z",
        hasNotificationPermission: true,
        onesignal_pushToken: "onesignal-push-token",
        onesignal_userId: "onesignal-user-id",
        latitude: 40.7128,
        longitude: -74.006,
        timezone: "America/New_York",
        currency: "USD",
        verification: true,
        denied_verification: false,
        verification_last_action: "2023-08-15T09:00:00Z",
        deleted: false,

    },
];

export { Users };