export const data = [
    {
        phone: "a",
        insta: {
            last_scrape: "Date",
            id: "String",
            access_token: "String",
            username: "a",
            full_name: "String",
            biography: "String",
            profile_pic: "String",
            followers: 0,
            following: 0,
            average_like: 0,
            post_number: 0,
            shared_posts: [
                {
                    media_url: "",
                    like_count: "",
                    comment_count: 0,
                    description: "",
                    location: {
                        name: "",
                        address: "",
                        city: "",
                        lng: 0,
                        lat: 0,
                    },
                    face_details: Schema.Types.Mixed,
                    moderation_labels: Schema.Types.Mixed,
                },
            ],
            keywords: [],
        },
        tiktok: {
            username: "",
            keywords: [],
            tiktok_last_scrape: "Date",
            tiktok_nickname: "String",
            bio_description: "String",
            last_scrape: "Date",
            followers: 0,
            following: 0,
            hearts: 0,
            videos: [
                {
                    like_count: 0,
                    comment_count: 0,
                    width: 0,
                    height: 0,
                    rate: 0,
                    download_count: 0,
                    play_count: 0,
                    share_count: 0,
                    whatsapp_share_count: 0,
                    forward_count: 0,
                    media_url: "",
                    music: "",
                    author: "",
                    album: "",
                    ratio: "",
                    description: "",
                    share_url: "",
                    region: "",
                    cover: "",
                    dynamicCover: "",
                },
            ],
            profile_pic: "String",
            createTime: "Date",
            privateAccount: true,
            verified: true,
            secret: true,
            tiktok_average_like: 0,
            tiktok_engagement_rate: 0,
            tiktok_access_token: "",
            tiktok_refresh_token: "",
            open_id: "",
            refresh_expires_in: "",
            log_id: "",
            union_id: ""
        },
        job: "",
        name: "",
        surname: "",
        score: 0,
        email: "",
        age: 0,
        gender: "",
        profile_complete: true,
        school_type: "",
        school_name: "",
        city: "",
        country: "",
        language: "",
        hobbies: "",
        latitude: 0,
        longitude: 0,
        timezone: "",
        currency: "",

        deviceInfo: { type: Schema.Types.Mixed, default: false }

    }


]